### ISSUE TITLE
Using deprecated #import

### ISSUE THREAD

**Issue by aglab2** [annamel/acroparallels2016#21]
Hello @ohld! Please fix issue with deprecated #import in your code. I attach example of warning:
`    /home/denisk/Documents/acroparallels2016/tester/../dokhlopkov/mapped_file/test/test_mf.c:1:2: warning: #import is a deprecated GCC extension [-Wdeprecated]
     #import <stdlib.h>
      ^
    /home/denisk/Documents/acroparallels2016/tester/../dokhlopkov/mapped_file/test/test_mf.c:2:2: warning: #import is a deprecated GCC extension [-Wdeprecated]
     #import <string.h>
      ^
    /home/denisk/Documents/acroparallels2016/tester/../dokhlopkov/mapped_file/test/test_mf.c:4:2: warning: #import is a deprecated GCC extension [-Wdeprecated]
     #import "../sources/mapped_file.h"`

**Comment by ohld** [comment]
Fixed in next version of my lib.
