### ISSUE TITLE
Add ranking based on test passage

### ISSUE THREAD

**Issue by ohld** [annamel/acroparallels2016#30]
Assign to me @ohld
Use 
* Mean and std values
* Best and worse algorithms 
* Failed tests

Any suggestions will be appreciated.

**Comment by aglab2** [comment]
I think that failed tests should part the biggest part of tests. Let's sort everyone by mean and give scores according to such  from 10 to 0 in current test. Everyone that are at std of best competitor gets equal highest  (10). If person didn't pass test, give negative  (-3 for timeout, -6 for fail).
