### ISSUE TITLE
Change filepath

### ISSUE THREAD

**Issue by karfly** [annamel/acroparallels2016#49]
par_tester.sh writes results to file 'par_test_result.txt' not to 'par_test_results.txt'
So it's better to remove 1 's' in par_test_results.ipynb filepath.

`data = pd.read_csv("par_test_result.txt", sep=' ', header=None, names=["lib", 'test', 'test_name', 'nth', 'time'])`

**Comment by ohld** [comment]
Last visualization notebook was called 'test_results.iphynb" that's why now new notebook was called this way. 
Wrong issue issigne. Refer to @aglab2
